language:
  - generic
  
dist: trusty

sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra -qq
  - sudo apt-get install texlive-luatex -qq
  - sudo apt-get install cm-super -qq
  - sudo apt-get install texlive-bibtex-extra -qq
  - sudo apt-get install latexmk -qq
  - sudo apt-get install tex4ht -qq
  - sudo apt-get install texlive-fonts-recommended -qq
  - sudo apt-get install texlive-lang-italian -qq
  
script:
  - latexmk -jobname=TecWeb2Project -pdflatex='pdflatex -interaction=nonstopmode' -pdf

after_failure:
  - cat main.log

before_deploy:
- git fetch --tags

deploy:
  provider: releases
  api_key:
    secure: AxFSISZxzgy6T0IiPMqq7kpSSrHtf4NZImyJVWMA7YJZgk1hmSifMcElEeVjHh8PLFu9PS9euq3jFNVYushkUy1erjXcfDIWCSjlkLgzpdBbkMDIuNND0q5QCl+GJlIJ5uSxwO8RtzmwEZ0U/7Eaw/eVTGi1W0yp4PznIjZIayobghf1gfsb2JI1VU7V26Toa/4DhQrM1JKqwq6jPqvcOWMhWzDDhTHiiPZNaAOyLonz34tW93dOnVH+aNrR4xxtvmkcWCZ/EdnoZcpyQgWNRCOJIscXwYw8190XREWcov9i6spojtd947MKB7TNYu6H+StxkvqO6rfShjyQvNrFMuE/7AeKYFhh/kjXpnHstOyjT3RgUr9BHzRgoDMtuOqJj81U35qxEg6szJM1fSdrPX5UFLQ3oELxKaogPPLejFIzPKU86RbFbKwZ3xRgYCcOmDIWjel4QiKflxlpOewdigcnUxFUhC+OSTPLObB1grG3IEuzr+QIQOAiI+3LqoWA7lCmBPmJzNBRJJ7Sdh8RE1tBCx5Eb+y/8+MM3QixAV8QUnRO+C/++vV1lBKkSiuMOZt5Ptt/eMI7oEAwqikrdcSD2ZCg+6hE+er7b6IuVVuvA5n9t4Kp2tFkhmtPFXQpFotEtxt/IqE2Cyr4hAd4+o/auQDEzlvtYab2fC4z8AA=
  file: TecWeb2Project.pdf
  skip_cleanup: true
  on:
    repo: Polpetta/TecWeb2Project
    tags: true
